import { getDatabase,type Database } from "../memory/db";

function shorten(value:string){if(value.length<=320)return value;const sentences=value.match(/[^.!?]+[.!?]+/g);return (sentences?.slice(0,2).join(" ") || value.slice(0,317)+"…").trim();}
function revisedContent(raw:Record<string,unknown>,target:string|null,instruction:string){const next=structuredClone(raw);const lower=instruction.toLocaleLowerCase("de-DE");let changed=false;
  if(target==="caption"&&typeof next.caption==="string"){next.caption=shorten(next.caption);changed=true;}
  if(target==="cta"&&typeof next.cta==="string"){next.cta=/weniger werblich|dezenter|nicht so werblich/.test(lower)?"Weitere Informationen findest du über den gekennzeichneten Link.":shorten(next.cta);changed=true;}
  if(target==="hook"&&typeof next.hook==="string"){next.hook=next.hook.replace(/^(wusstest du|kennst du das|hast du dich schon gefragt)[,:?\s-]*/i,"").replace(/^./,c=>c.toUpperCase());changed=true;}
  if(!changed)throw new Error("Diese Änderung lässt sich ohne neue kreative Ausarbeitung nicht sicher automatisch anwenden.");
  next.revisionInstruction=instruction;return next;
}

export function contentApprovalRepository(db:Database=getDatabase()){return {
  async submit(jobId:string,senderHash:string){return db.transaction(async sql=>{const job=await sql.query("SELECT snapshot,status FROM content_jobs WHERE id=$1 FOR UPDATE",[jobId]);if(!job.rows.length)throw new Error("Content-Job nicht gefunden.");if(job.rows[0].status!=="approved")throw new Error("Content-Plan muss zuerst freigegeben sein.");const snapshot=job.rows[0].snapshot as {content?:Record<string,unknown>;opportunity?:{targetPlatform?:string;product?:{name?:string}}};if(!snapshot.content)throw new Error("Content fehlt im gespeicherten Job.");const format=String(snapshot.content.format);if(format==="video")throw new Error("Video-Content wird erst nach erfolgreicher Produktion vorgelegt.");const existing=await sql.query("SELECT v.id AS content_version_id,a.id AS approval_id,v.content FROM content_versions v JOIN approval_requests a ON a.content_version_id=v.id WHERE v.job_id=$1 AND a.status='AWAITING_HUMAN_APPROVAL' ORDER BY v.version DESC LIMIT 1",[jobId]);if(existing.rows.length)return existing.rows[0];const versionResult=await sql.query("SELECT COALESCE(max(version),0)+1 AS version FROM content_versions WHERE job_id=$1",[jobId]);const id=crypto.randomUUID(),approvalId=crypto.randomUUID(),now=new Date().toISOString(),content={...snapshot.content,product:snapshot.opportunity?.product?.name || "Unbekannt"};await sql.query("INSERT INTO content_versions(id,job_id,version,format,platform,content,status,created_at) VALUES($1,$2,$3,$4,$5,$6,'awaiting_approval',$7)",[id,jobId,Number(versionResult.rows[0].version),format,snapshot.opportunity?.targetPlatform==="facebook"?"facebook":"instagram",JSON.stringify(content),now]);await sql.query("INSERT INTO approval_requests(id,kind,content_version_id,payload,status,created_at) VALUES($1,'CONTENT_PUBLISH',$2,$3,'AWAITING_HUMAN_APPROVAL',$4)",[approvalId,id,JSON.stringify(content),now]);if(senderHash){await sql.query("UPDATE conversation_contexts SET status='closed',updated_at=$2 WHERE sender_hash=$1 AND status='open'",[senderHash,now]);await sql.query("INSERT INTO conversation_contexts(id,sender_hash,approval_request_id,status,created_at,updated_at) VALUES($1,$2,$3,'open',$4,$4)",[crypto.randomUUID(),senderHash,approvalId,now]);}return {content_version_id:id,approval_id:approvalId,content};});},
  async revise(versionId:string,target:string|null,instruction:string,senderHash:string){return db.transaction(async sql=>{const old=await sql.query("SELECT * FROM content_versions WHERE id=$1 FOR UPDATE",[versionId]);if(!old.rows.length)throw new Error("Content-Version nicht gefunden.");const content=revisedContent(old.rows[0].content as Record<string,unknown>,target,instruction);const next=await sql.query("SELECT COALESCE(max(version),0)+1 AS version FROM content_versions WHERE job_id=$1",[old.rows[0].job_id]);const id=crypto.randomUUID(),approvalId=crypto.randomUUID(),now=new Date().toISOString();await sql.query("UPDATE content_versions SET status='revision_requested' WHERE id=$1",[versionId]);await sql.query("UPDATE approval_requests SET status='REVISION_REQUESTED',decision_text=$2,decided_at=$3 WHERE content_version_id=$1 AND status='AWAITING_HUMAN_APPROVAL'",[versionId,instruction,now]);await sql.query("UPDATE conversation_contexts SET status='closed',updated_at=$2 WHERE approval_request_id IN (SELECT id FROM approval_requests WHERE content_version_id=$1)",[versionId,now]);await sql.query("INSERT INTO content_versions(id,job_id,version,format,platform,content,status,created_at) VALUES($1,$2,$3,$4,$5,$6,'awaiting_approval',$7)",[id,old.rows[0].job_id,Number(next.rows[0].version),old.rows[0].format,old.rows[0].platform,JSON.stringify(content),now]);await sql.query("INSERT INTO approval_requests(id,kind,content_version_id,payload,status,created_at) VALUES($1,'CONTENT_PUBLISH',$2,$3,'AWAITING_HUMAN_APPROVAL',$4)",[approvalId,id,JSON.stringify(content),now]);if(senderHash)await sql.query("INSERT INTO conversation_contexts(id,sender_hash,approval_request_id,status,created_at,updated_at) VALUES($1,$2,$3,'open',$4,$4)",[crypto.randomUUID(),senderHash,approvalId,now]);return {contentVersionId:id,approvalId,content};});},
};}
