const {test}=require('node:test');
const assert=require('node:assert/strict');
const {PGlite}=require('@electric-sql/pglite');
const {applyMigrations}=require('../.test-build/lib/memory/migrations');
const dbModule=require('../.test-build/lib/memory/db');
const whatsapp=require('../.test-build/lib/whatsapp/client');
const {memoryRepository}=require('../.test-build/lib/memory/repository');
const {productionRepository}=require('../.test-build/lib/production/repository');
const {runContentJob}=require('../.test-build/lib/content/orchestrator');
const {opportunitySchema}=require('../.test-build/lib/content/schema');
const {requestContentApproval,handleContentApproval,hasContentApproval}=require('../.test-build/lib/whatsapp/content-approval');

test('WhatsApp approves the exact finished script before any video production can be prepared',async t=>{
  const pg=new PGlite();t.after(()=>pg.close());
  const db={query:(q,v)=>pg.query(q,v),exec:q=>pg.exec(q),transaction:fn=>pg.transaction(tx=>fn({query:(q,v)=>tx.query(q,v),exec:q=>tx.exec(q)}))};
  await applyMigrations(db);
  t.mock.method(dbModule,'getDatabase',()=>db);
  const old=process.env.WHATSAPP_APPROVER_WA_ID;process.env.WHATSAPP_APPROVER_WA_ID='491234';
  t.after(()=>{if(old===undefined)delete process.env.WHATSAPP_APPROVER_WA_ID;else process.env.WHATSAPP_APPROVER_WA_ID=old;});
  const sent=[];
  t.mock.method(whatsapp,'sendWhatsAppText',async message=>{sent.push(message);return `wamid.content.${sent.length}`;});
  const memory=memoryRepository(db),repo=productionRepository(db),id=crypto.randomUUID();
  const opportunity=opportunitySchema.parse({product:{name:'YAVOCOS Kürbis Schnitzset',productVerifiedName:'YAVOCOS Kürbis Schnitzset',productVerifiedAt:'2026-09-26T08:00:00.000Z',sourceUrl:'https://www.amazon.de/dp/B0D9YQR9CT',affiliateUrl:'',price:'',targetGroup:'Halloween-Bastler',benefits:'Produktdetails prüfen',notes:''},useCase:'Ein Erwachsener schnitzt mit dem Werkzeug eine Halloween-Laterne.',category:'home_living',targetPlatform:'instagram',budget:'quality'});
  await memory.claim(id,opportunity,'reference');
  const draft=await runContentJob(opportunity,{id,allowedFormats:['video'],onUpdate:memory.save});
  assert.equal(draft.status,'awaiting_approval');
  await assert.rejects(repo.prepareVideo(id),/freigegeben/);
  await db.query("INSERT INTO whatsapp_events(message_id,wa_id,body,payload) VALUES('wamid.open-window','491234','Entwurf','{}')");
  const first=await requestContentApproval(id);
  assert.match(sent[0],/Drehbuch/);
  assert.match(sent[0],/Inhaltsfreigabe/);
  assert.equal((await handleContentApproval({id:'wamid.change',from:'491234',body:'Kinder dürfen beim Zeichnen des Kürbisgesichts dabei sein, die erwachsene Person schneidet.',replyToMessageId:first.messageId,payload:{}})),true);
  const changed=(await memory.list()).find(job=>job.id===id);
  assert.equal(changed.status,'awaiting_approval');
  assert.match(changed.content.scenes.map(scene=>scene.visual).join(' '),/Kind/);
  assert.equal(await hasContentApproval(changed,db),false);
  assert.equal((await db.query("SELECT status FROM content_approval_requests WHERE id=$1",[first.id])).rows[0].status,'changes_requested');
  const pending=await db.query("SELECT whatsapp_message_id FROM content_approval_requests WHERE job_id=$1 AND status='pending'",[id]);
  assert.equal(pending.rows.length,1);
  assert.equal((await handleContentApproval({id:'wamid.old',from:'491234',body:'Freigeben',replyToMessageId:first.messageId,payload:{}})),true);
  await assert.rejects(repo.prepareVideo(id),/freigegeben/);
  assert.equal((await handleContentApproval({id:'wamid.new',from:'491234',body:'Freigeben',replyToMessageId:pending.rows[0].whatsapp_message_id,payload:{}})),true);
  const approved=(await memory.list()).find(job=>job.id===id);
  assert.equal(approved.status,'approved');
  assert.equal(await hasContentApproval(approved,db),true);
  assert.equal((await repo.prepareVideo(id)).run.status,'needs_provider_quote');
  assert.equal((await db.query('SELECT count(*)::int AS n FROM production_runs')).rows[0].n,1);
});
