const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const {PGlite}=require('@electric-sql/pglite');
const {memoryRepository}=require('../.test-build/lib/memory/repository');
const {productionRepository}=require('../.test-build/lib/production/repository');
const {publicationRepository}=require('../.test-build/lib/meta/publication-gate');
const {runContentJob}=require('../.test-build/lib/content/orchestrator');
const {opportunitySchema}=require('../.test-build/lib/content/schema');

test('Facebook publication needs a distinct signed WhatsApp decision and claims exactly one external POST',async()=>{
  const pg=new PGlite();
  const db={query:(q,v)=>pg.query(q,v),exec:q=>pg.exec(q),transaction:fn=>pg.transaction(tx=>fn({query:(q,v)=>tx.query(q,v),exec:q=>tx.exec(q)}))};
  const old=process.env.WHATSAPP_APPROVER_WA_ID;process.env.WHATSAPP_APPROVER_WA_ID='491234';
  try{
    for(const file of ['001_memory.sql','002_production_gates.sql','003_faceless_so.sql','004_daily_drafts.sql','005_publication_gate.sql','006_daily_notification.sql','007_publication_revisions.sql','008_weekly_reports.sql'])await pg.exec(fs.readFileSync(`db/migrations/${file}`,'utf8'));
    const memory=memoryRepository(db),publication=publicationRepository(db),inbound=productionRepository(db);
    const opportunity=opportunitySchema.parse({product:{productVerifiedAt:'2026-09-26T08:00:00.000Z', productVerifiedName:'Kuscheldecke', name:'Kuscheldecke',sourceUrl:'https://www.amazon.de/dp/B000000001',affiliateUrl:'https://www.amazon.de/dp/B000000001',price:'',targetGroup:'Haushalte',benefits:'Größe und Material vergleichen',notes:''},useCase:'Ein kühler Herbstabend auf dem Sofa mit einer Decke.',targetPlatform:'facebook',budget:'low'});
    const id=crypto.randomUUID();await memory.claim(id,opportunity,'reference');
    const job=await runContentJob(opportunity,{id,onUpdate:memory.save,loadLearning:memory.learn});
    assert.equal(job.content.format,'image');await memory.approve(id);
    const pending=await publication.prepare(id,'491234');
    assert.equal(pending.status,'preparing');assert.equal((await publication.prepare(id,'491234')).id,pending.id);
    const groupOpportunity={...opportunity,goal:'community'};
    const groupId=crypto.randomUUID();await memory.claim(groupId,groupOpportunity,'reference');
    const groupJob=await runContentJob(groupOpportunity,{id:groupId,onUpdate:memory.save,loadLearning:memory.learn});
    assert.equal(groupJob.marketing.primary,'Gruppenbeitrag');await memory.approve(groupId);
    await assert.rejects(publication.prepare(groupId,'491234'),/Gruppenbeitrag.*Facebook-Seite/);
    const instagramOpportunity={...opportunity,targetPlatform:'instagram'};
    const instagramId=crypto.randomUUID();await memory.claim(instagramId,instagramOpportunity,'reference');
    await runContentJob(instagramOpportunity,{id:instagramId,onUpdate:memory.save,loadLearning:memory.learn});await memory.approve(instagramId);
    await assert.rejects(publication.prepare(instagramId,'491234'),/nicht für Facebook geplant/);
    assert.equal((await pg.query('SELECT count(*)::int AS count FROM publication_requests')).rows[0].count,1,'ineligible jobs must not create publication requests');
    await assert.rejects(publication.claimPublish(pending.id),/nicht freigegeben/);
    await publication.claimImage(pending.id);
    await publication.bindImage(pending.id,'https://example.public.blob.vercel-storage.com/image.png');
    await publication.claimWhatsAppSend(pending.id);
    await publication.bindMessage(pending.id,'wamid.publish');
    const stranger=await inbound.applyIncomingWhatsApp({id:'wamid.stranger',from:'499999',body:'Freigeben',replyToMessageId:'wamid.publish',payload:{}});
    assert.equal(stranger.reason,'untrusted_sender');
    const weak=await inbound.applyIncomingWhatsApp({id:'wamid.weak',from:'491234',body:'ja',replyToMessageId:'wamid.publish',payload:{}});
    assert.notEqual(weak.intent,'approve');
    assert.equal((await publication.get(id)).status,'changes_requested');
    await assert.rejects(publication.claimPublish(pending.id),/nicht freigegeben/);
    const id2=crypto.randomUUID();await memory.claim(id2,opportunity,'reference');
    await runContentJob(opportunity,{id:id2,onUpdate:memory.save,loadLearning:memory.learn});await memory.approve(id2);
    const next=await publication.prepare(id2,'491234');await publication.claimImage(next.id);
    await publication.bindImage(next.id,'https://example.public.blob.vercel-storage.com/image.png');await publication.claimWhatsAppSend(next.id);await publication.bindMessage(next.id,'wamid.publish2');
    const approved=await inbound.applyIncomingWhatsApp({id:'wamid.approve',from:'491234',body:'OK, freigeben',replyToMessageId:'wamid.publish2',payload:{}});
    assert.equal(approved.publicationId,next.id);assert.equal(approved.intent,'approve');
    assert.equal((await inbound.applyIncomingWhatsApp({id:'wamid.approve',from:'491234',body:'OK, freigeben',replyToMessageId:'wamid.publish2',payload:{}})).reason,'duplicate');
    assert.equal((await publication.claimPublish(next.id)).status,'publishing');
    await assert.rejects(publication.claimPublish(next.id),/bereits versucht/);
    await publication.markUnknown(next.id);
    assert.equal((await publication.get(id2)).status,'unknown');
    const id3=crypto.randomUUID();await memory.claim(id3,opportunity,'reference');
    await runContentJob(opportunity,{id:id3,onUpdate:memory.save,loadLearning:memory.learn});
    await pg.query("INSERT INTO daily_drafts(day,job_id,status,whatsapp_send_attempted_at,whatsapp_message_id) VALUES('2026-09-24',$1,'awaiting_approval',now(),'wamid.daily')",[id3]);
    const daily=await inbound.applyIncomingWhatsApp({id:'wamid.daily.approve',from:'491234',body:'Freigeben',replyToMessageId:'wamid.daily',payload:{}});
    assert.equal(daily.dailyJobId,id3);assert.equal(daily.intent,'approve');
    assert.equal((await memory.list()).find(row=>row.id===id3).status,'approved');
    assert.equal((await pg.query("SELECT status FROM daily_drafts WHERE job_id=$1",[id3])).rows[0].status,'content_approved');
    assert.equal((await publication.get(id3)),null,'content approval cannot post without a second WhatsApp decision');
    const id4=crypto.randomUUID();await memory.claim(id4,opportunity,'reference');
    await runContentJob(opportunity,{id:id4,onUpdate:memory.save,loadLearning:memory.learn});
    await pg.query("INSERT INTO daily_drafts(day,job_id,status,notification_send_attempted_at,notification_message_id) VALUES('2026-09-25',$1,'awaiting_approval',now(),'wamid.notice')",[id4]);
    const untrusted=await inbound.applyIncomingWhatsApp({id:'wamid.notice.stranger',from:'499999',body:'Entwurf',replyToMessageId:'wamid.notice',payload:{}});
    assert.equal(untrusted.reason,'untrusted_sender');
    const premature=await inbound.applyIncomingWhatsApp({id:'wamid.notice.premature',from:'491234',body:'Freigeben',replyToMessageId:'wamid.notice',payload:{}});
    assert.equal(premature.reason,'notification_requires_entwurf');
    assert.equal((await memory.list()).find(row=>row.id===id4).status,'awaiting_approval');
    const requested=await inbound.applyIncomingWhatsApp({id:'wamid.notice.reply',from:'491234',body:'Entwurf',replyToMessageId:'wamid.notice',payload:{}});
    assert.equal(requested.dailyNotificationJobId,id4);
    assert.equal((await inbound.applyIncomingWhatsApp({id:'wamid.notice.reply',from:'491234',body:'Entwurf',replyToMessageId:'wamid.notice',payload:{}})).reason,'duplicate');
    assert.equal((await memory.list()).find(row=>row.id===id4).status,'awaiting_approval');
    await pg.query("UPDATE daily_drafts SET whatsapp_send_attempted_at=now(),whatsapp_message_id='wamid.full-draft' WHERE job_id=$1",[id4]);
    assert.equal((await inbound.applyIncomingWhatsApp({id:'wamid.notice.late',from:'491234',body:'Freigeben',replyToMessageId:'wamid.notice',payload:{}})).reason,'no_pending_approval');
    const actual=await inbound.applyIncomingWhatsApp({id:'wamid.full.approve',from:'491234',body:'Freigeben',replyToMessageId:'wamid.full-draft',payload:{}});
    assert.equal(actual.dailyJobId,id4);
    assert.equal((await memory.list()).find(row=>row.id===id4).status,'approved');
    assert.equal(await publication.get(id4),null,'notification and first approval cannot publish');
    const id5=crypto.randomUUID();await memory.claim(id5,opportunity,'reference');
    await runContentJob(opportunity,{id:id5,onUpdate:memory.save,loadLearning:memory.learn});
    await pg.query("INSERT INTO daily_drafts(day,job_id,status,whatsapp_message_id,feedback) VALUES('2026-09-26',$1,'changes_requested','wamid.recovery','Freigegeben')",[id5]);
    const recovered=await inbound.applyIncomingWhatsApp({id:'wamid.recovery.reply',from:'491234',body:'Freigeben',replyToMessageId:'wamid.recovery',payload:{}});
    assert.equal(recovered.dailyJobId,id5);assert.equal(recovered.intent,'approve');
    assert.equal((await memory.list()).find(row=>row.id===id5).status,'approved');
    assert.equal(await publication.get(id5),null,'recovery does not publish');
    const id6=crypto.randomUUID();await memory.claim(id6,opportunity,'reference');
    await runContentJob(opportunity,{id:id6,onUpdate:memory.save,loadLearning:memory.learn});
    await pg.query("INSERT INTO daily_drafts(day,job_id,status,whatsapp_message_id,feedback) VALUES('2026-09-27',$1,'changes_requested','wamid.real-change','Neues Bild bitte')",[id6]);
    assert.equal((await inbound.applyIncomingWhatsApp({id:'wamid.real-change.reply',from:'491234',body:'Freigeben',replyToMessageId:'wamid.real-change',payload:{}})).reason,'no_pending_approval');
    assert.equal((await memory.list()).find(row=>row.id===id6).status,'awaiting_approval');
  }finally{if(old===undefined)delete process.env.WHATSAPP_APPROVER_WA_ID;else process.env.WHATSAPP_APPROVER_WA_ID=old;await pg.close();}
});
