const {test}=require('node:test');
const assert=require('node:assert/strict');
const {PGlite}=require('@electric-sql/pglite');
const {applyMigrations}=require('../.test-build/lib/memory/migrations');
const dbModule=require('../.test-build/lib/memory/db');
const whatsapp=require('../.test-build/lib/whatsapp/client');
const runway=require('../.test-build/lib/production/runway-story');
const {memoryRepository}=require('../.test-build/lib/memory/repository');
const {productionRepository}=require('../.test-build/lib/production/repository');
const {runContentJob}=require('../.test-build/lib/content/orchestrator');
const {opportunitySchema}=require('../.test-build/lib/content/schema');
const {requestContentApproval,handleContentApproval}=require('../.test-build/lib/whatsapp/content-approval');
const {requestVideoCostApproval}=require('../.test-build/lib/production/request-cost-approval');

test('one WhatsApp content approval automatically requests a bounded video quote without a studio action',async t=>{
  const pg=new PGlite();t.after(()=>pg.close());
  const db={query:(q,v)=>pg.query(q,v),exec:q=>pg.exec(q),transaction:fn=>pg.transaction(tx=>fn({query:(q,v)=>tx.query(q,v),exec:q=>tx.exec(q)}))};
  await applyMigrations(db);t.mock.method(dbModule,'getDatabase',()=>db);
  const previous={wa:process.env.WHATSAPP_APPROVER_WA_ID,runway:process.env.RUNWAYML_API_SECRET};
  process.env.WHATSAPP_APPROVER_WA_ID='4912345678';process.env.RUNWAYML_API_SECRET='test-only';
  t.after(()=>{for(const [key,value] of [['WHATSAPP_APPROVER_WA_ID',previous.wa],['RUNWAYML_API_SECRET',previous.runway]])if(value===undefined)delete process.env[key];else process.env[key]=value;});
  const sent=[];
  t.mock.method(whatsapp,'whatsappApprovalReady',()=>true);
  t.mock.method(whatsapp,'sendWhatsAppText',async body=>{sent.push(body);return `wamid.auto.${sent.length}`;});
  let quotes=0;
  t.mock.method(runway,'runwayStoryClient',()=>({quote:async()=>{quotes++;return{credits:300,balance:500,estimatedUsd:3};}}));
  const id=crypto.randomUUID(),memory=memoryRepository(db),repo=productionRepository(db);
  const opportunity=opportunitySchema.parse({product:{name:'YAVOCOS Kürbis Schnitzset',productVerifiedName:'YAVOCOS Kürbis Schnitzset',productVerifiedAt:'2026-09-26T08:00:00Z',sourceUrl:'https://www.amazon.de/dp/B0D9YQR9CT',affiliateUrl:'',price:'',targetGroup:'Halloween-Bastler',benefits:'Hinweise prüfen',notes:''},useCase:'Ein Erwachsener schnitzt einen echten Halloween-Kürbis.',category:'home_living',targetPlatform:'instagram',budget:'quality'});
  await memory.claim(id,opportunity,'reference');await runContentJob(opportunity,{id,allowedFormats:['video'],onUpdate:memory.save});
  await db.query("INSERT INTO whatsapp_events(message_id,wa_id,body,payload) VALUES('wamid.open','4912345678','Entwurf','{}')");
  const content=await requestContentApproval(id);
  assert.match(sent[0],/Affiliate-Produktlink \(als Text\): https:/);
  await handleContentApproval({id:'wamid.inbound',from:'4912345678',body:'Freigabe',replyToMessageId:content.messageId,payload:{}},requestVideoCostApproval);
  assert.equal(quotes,1);
  assert.match(sent.at(-1),/300 Credits/);
  assert.equal((await repo.getByJobId(id)).status,'awaiting_whatsapp_approval');
  assert.equal((await db.query('SELECT count(*)::int AS n FROM production_runs WHERE provider_request_attempted_at IS NOT NULL')).rows[0].n,0);
  await requestVideoCostApproval(id);
  assert.equal(quotes,1,'pending quote is reused');
  assert.equal(sent.length,3,'one content message, one acknowledgement, one cost message');
  const cost=await repo.latestApproval(id);
  const decision=await repo.applyIncomingWhatsApp({id:'wamid.cost.approve',from:'4912345678',body:'Freigabe',replyToMessageId:cost.whatsappMessageId,payload:{}});
  assert.equal(decision.intent,'approve');
  assert.equal((await repo.getByJobId(id)).status,'approved_for_spend');
  assert.equal((await db.query('SELECT count(*)::int AS n FROM production_runs WHERE provider_request_attempted_at IS NOT NULL')).rows[0].n,0,'cost approval alone has not caused a duplicate paid POST');
});
