import { getDatabase,type Database } from "../memory/db";

function berlinParts(date:Date){const parts=new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Berlin",year:"numeric",month:"2-digit",day:"2-digit",weekday:"short",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(date);return Object.fromEntries(parts.map(p=>[p.type,p.value])) as Record<string,string>;}
function localMidnightUtc(year:number,month:number,day:number){let guess=Date.UTC(year,month-1,day);for(let i=0;i<3;i++){const p=berlinParts(new Date(guess));const represented=Date.UTC(Number(p.year),Number(p.month)-1,Number(p.day),Number(p.hour),Number(p.minute));guess-=represented-Date.UTC(year,month-1,day);}return new Date(guess);}
export function berlinWeek(now=new Date()){const p=berlinParts(now),date=new Date(Date.UTC(Number(p.year),Number(p.month)-1,Number(p.day)));const day=(date.getUTCDay()+6)%7;const monday=new Date(date);monday.setUTCDate(date.getUTCDate()-day);const next=new Date(monday);next.setUTCDate(monday.getUTCDate()+7);const previous=new Date(monday);previous.setUTCDate(monday.getUTCDate()-7);return {start:localMidnightUtc(monday.getUTCFullYear(),monday.getUTCMonth()+1,monday.getUTCDate()),end:localMidnightUtc(next.getUTCFullYear(),next.getUTCMonth()+1,next.getUTCDate()),previousStart:localMidnightUtc(previous.getUTCFullYear(),previous.getUTCMonth()+1,previous.getUTCDate()),local:p};}
const euro=(cents:number)=>`${(cents/100).toFixed(2).replace(".",",")} €`;

export async function weeklyReport(db:Database=getDatabase(),now=new Date()){
  const range=berlinWeek(now),args=[range.start.toISOString(),range.end.toISOString()];
  const [production,publications,metrics,previous,open]=await Promise.all([
    db.query(`SELECT provider,count(*) FILTER (WHERE status='completed') AS completed,COALESCE(sum(actual_cost_cents) FILTER (WHERE status='completed'),0) AS cost_cents,count(actual_cost_cents) FILTER (WHERE status='completed') AS known_costs FROM production_requests WHERE created_at >= $1 AND created_at < $2 GROUP BY provider`,args),
    db.query(`SELECT count(*) FILTER (WHERE status='published') AS published,count(*) FILTER (WHERE status='published' AND j.content_type='text') AS text_posts FROM publications p JOIN content_jobs j ON j.id=p.job_id WHERE p.published_at >= $1 AND p.published_at < $2`,args),
    db.query(`SELECT COALESCE(sum(o.views),0) views,COALESCE(sum(o.impressions),0) impressions,COALESCE(sum(o.clicks),0) clicks,COALESCE(sum(o.conversions),0) conversions,COALESCE(sum(o.orders),0) orders,COALESCE(sum(o.affiliate_revenue_cents),0) revenue_cents,COALESCE(sum(o.new_followers),0) new_followers,max(o.follower_total) follower_total,count(*) observations
      FROM publications p JOIN LATERAL (SELECT * FROM performance_observations x WHERE x.publication_id=p.id ORDER BY revision DESC LIMIT 1) o ON true WHERE o.observed_at >= $1 AND o.observed_at < $2`,args),
    db.query(`SELECT COALESCE(sum(o.views),0) views,COALESCE(sum(o.clicks),0) clicks FROM publications p JOIN LATERAL (SELECT * FROM performance_observations x WHERE x.publication_id=p.id ORDER BY revision DESC LIMIT 1) o ON true WHERE o.observed_at >= $1 AND o.observed_at < $2`,[range.previousStart.toISOString(),range.start.toISOString()]),
    db.query(`SELECT (SELECT count(*) FROM approval_requests WHERE status='AWAITING_HUMAN_APPROVAL') approvals,(SELECT count(*) FROM capability_proposals WHERE status='AWAITING_HUMAN_APPROVAL') proposals`,[]),
  ]);
  const providers=Object.fromEntries(production.rows.map(r=>[String(r.provider),{completed:Number(r.completed),costCents:Number(r.cost_cents),knownCosts:Number(r.known_costs)}]));const current=metrics.rows[0]||{},prev=previous.rows[0]||{};const totalCost=Object.values(providers).reduce((sum,p)=>sum+p.costCents,0),revenue=Number(current.revenue_cents||0),clicks=Number(current.clicks||0),conversions=Number(current.conversions||0),impressions=Number(current.impressions||0);
  const data={periodStart:range.start.toISOString(),periodEnd:range.end.toISOString(),producedVideos:Object.values(providers).reduce((s,p)=>s+p.completed,0),publishedVideos:Number(publications.rows[0]?.published||0)-Number(publications.rows[0]?.text_posts||0),publishedTextPosts:Number(publications.rows[0]?.text_posts||0),providers,views:Number(current.views||0),impressions,clicks,ctr:impressions?clicks/impressions:null,newFollowers:Number(current.new_followers||0),followerTotal:current.follower_total==null?null:Number(current.follower_total),conversions,orders:current.orders==null?null:Number(current.orders),conversionRate:clicks?conversions/clicks:null,revenueCents:revenue,totalCostCents:totalCost,resultCents:revenue-totalCost,observations:Number(current.observations||0),previousViews:Number(prev.views||0),previousClicks:Number(prev.clicks||0),openApprovals:Number(open.rows[0]?.approvals||0),openProposals:Number(open.rows[0]?.proposals||0)};
  const endDisplay=new Date(range.end.getTime()-1);const date=(d:Date)=>new Intl.DateTimeFormat("de-DE",{timeZone:"Europe/Berlin",day:"2-digit",month:"2-digit",year:"numeric"}).format(d);
  const providerLines=Object.entries(providers).map(([name,p])=>`${name}: ${p.completed} Videos, ${p.knownCosts===p.completed?euro(p.costCents):"Kosten teilweise nicht automatisch verfügbar"}`).join("\n")||"Keine Produktion";
  const affiliate=data.observations?`${clicks} Klicks\n${conversions} Conversions\nBestellungen: ${data.orders ?? "Daten noch nicht automatisch verfügbar"}\nProvision/Umsatz: ${euro(revenue)}`:"Daten noch nicht automatisch verfügbar";
  const message=`WOCHENBILANZ\n${date(range.start)}–${date(endDisplay)}\n\nCONTENT\n${data.producedVideos} Videos produziert\n${data.publishedVideos} Videos veröffentlicht\n${data.publishedTextPosts} Text-Posts veröffentlicht\n${providerLines}\n\nREICHWEITE\n${data.views} Views\n${impressions} Impressions\n${clicks} Klicks\nCTR: ${data.ctr===null?"nicht verfügbar":(data.ctr*100).toFixed(1).replace(".",",")+" %"}\nNeue Follower: ${data.followerTotal===null?"Daten noch nicht automatisch verfügbar":data.newFollowers}\nFollower gesamt: ${data.followerTotal ?? "Daten noch nicht automatisch verfügbar"}\n\nAFFILIATE\n${affiliate}\n\nFINANZEN\nEinnahmen: ${data.observations?euro(revenue):"Daten noch nicht automatisch verfügbar"}\nAusgaben: ${euro(totalCost)}${Object.values(providers).some(p=>p.knownCosts<p.completed)?" (teilweise unbekannt)":""}\nErgebnis: ${data.observations?euro(data.resultCents):"nicht berechenbar"}\n\nVeränderung zur Vorwoche\nViews: ${data.views-data.previousViews>=0?"+":""}${data.views-data.previousViews}\nKlicks: ${clicks-data.previousClicks>=0?"+":""}${clicks-data.previousClicks}\n\nOffene Freigaben: ${data.openApprovals}\nOffene Capability Proposals: ${data.openProposals}`;
  return {range,data,message};
}
