import { z } from "zod";import { getDatabase,type Database } from "../memory/db";import { metaConfig } from "./connection";
type Job=Record<string,unknown>&{id:string;content_version_id:string;platform:"instagram"|"facebook";status:string;external_container_id:string|null;external_media_id:string|null;provider_state:Record<string,unknown>;content:Record<string,unknown>;version_platform:string|null};
const idResponse=z.object({id:z.string()});
function config(){const value=metaConfig();if(!value.token||!value.instagramId||!value.pageId)throw new Error("Meta Publishing benötigt Token, Instagram-ID und Seiten-ID im Server-Environment.");return value as Required<Pick<typeof value,"token"|"instagramId"|"pageId">>&typeof value;}
async function graph(path:string,method:"GET"|"POST",body?:Record<string,string>){const c=config(),url=new URL(`https://graph.facebook.com/${c.version||"v25.0"}/${path}`);const init:RequestInit={method,headers:{Authorization:`Bearer ${c.token}`},redirect:"error",signal:AbortSignal.timeout(20_000)};if(method==="POST"){init.headers={...init.headers,"Content-Type":"application/x-www-form-urlencoded"};init.body=new URLSearchParams(body);}else for(const [k,v] of Object.entries(body||{}))url.searchParams.set(k,v);const response=await fetch(url,init);let json:unknown;try{json=await response.json();}catch{json={};}if(!response.ok)throw Object.assign(new Error("Meta Publishing API hat die Anfrage abgelehnt."),{status:response.status});return json;}
export function publishingRepository(db:Database=getDatabase()){return {
  async create(contentVersionId:string,platform:"instagram"|"facebook"){return db.transaction(async sql=>{const version=await sql.query("SELECT * FROM content_versions WHERE id=$1 FOR SHARE",[contentVersionId]);if(!version.rows.length)throw new Error("Content-Version nicht gefunden.");if(version.rows[0].status!=="approved")throw new Error("Ohne ausdrückliche Content-Freigabe ist Publishing gesperrt.");if(version.rows[0].platform&&version.rows[0].platform!==platform)throw new Error("Freigabe gilt nicht für diese Plattform.");const content=version.rows[0].content as Record<string,unknown>;const format=String(version.rows[0].format);if(format==="video"&&(typeof content.videoUrl!=="string"||!content.videoUrl.startsWith("https://")))throw new Error("Freigegebene Video-URL fehlt.");if(format==="text"&&platform!=="facebook")throw new Error("Instagram unterstützt keinen reinen Text-Post.");if(format==="image")throw new Error("Bild-/Carousel-Publishing ist in dieser stabilen Phase noch nicht aktiviert.");const existing=await sql.query("SELECT id FROM publishing_jobs WHERE content_version_id=$1 AND platform=$2",[contentVersionId,platform]);if(existing.rows.length)return String(existing.rows[0].id);const id=crypto.randomUUID();await sql.query("INSERT INTO publishing_jobs(id,content_version_id,platform,status) VALUES($1,$2,$3,'approved')",[id,contentVersionId,platform]);return id;});},
  async get(id:string){const r=await db.query("SELECT p.*,v.content,v.platform AS version_platform FROM publishing_jobs p JOIN content_versions v ON v.id=p.content_version_id WHERE p.id=$1",[id]);return r.rows[0] as Job|undefined;},
  async claim(id:string,from:string,to:string){const r=await db.query("UPDATE publishing_jobs SET status=$3,updated_at=now() WHERE id=$1 AND status=$2 RETURNING id",[id,from,to]);return r.rows.length===1;},
  async update(id:string,fields:Record<string,unknown>){const allowed=new Set(["status","external_container_id","external_media_id","provider_state","permalink","error_code","error_message","published_at"]);const entries=Object.entries(fields).filter(([k])=>allowed.has(k));const values=entries.map(([,v])=>v);const sets=entries.map(([k],i)=>`${k}=$${i+2}`);if(entries.length)await db.query(`UPDATE publishing_jobs SET ${sets.join(",")},updated_at=now() WHERE id=$1`,[id,...values]);},
  async finalize(job:Job,mediaId:string,permalink:string|null){return db.transaction(async sql=>{const now=new Date().toISOString();await sql.query("UPDATE publishing_jobs SET status='published',external_media_id=$2,permalink=$3,published_at=$4,updated_at=$4 WHERE id=$1",[job.id,mediaId,permalink,now]);await sql.query("UPDATE content_versions SET status='published',published_at=$2 WHERE id=$1",[job.content_version_id,now]);const version=await sql.query("SELECT job_id FROM content_versions WHERE id=$1",[job.content_version_id]);if(version.rows[0]?.job_id)await sql.query(`INSERT INTO publications(id,job_id,platform,status,url,published_at) VALUES($1,$2,$3,'published',$4,$5) ON CONFLICT(job_id,platform) DO UPDATE SET status='published',url=EXCLUDED.url,published_at=EXCLUDED.published_at,updated_at=now()`,[crypto.randomUUID(),version.rows[0].job_id,job.platform,permalink||`https://${job.platform}.com/`,now]);});},
};}

export async function advancePublishing(id:string){const repo=publishingRepository();let job=await repo.get(id);if(!job)throw new Error("Publishing-Job nicht gefunden.");const content=job.content,videoUrl=String(content.videoUrl||""),caption=[content.caption,content.cta,content.disclosure].filter(Boolean).join("\n\n").slice(0,2200),c=config();
  try{
    if(job.platform==="facebook"&&!videoUrl){
      if(job.status==="approved"&&await repo.claim(id,"approved","publishing")){const message=[content.body,content.caption,content.cta,content.disclosure].filter(Boolean).join("\n\n").slice(0,60000);const post=idResponse.parse(await graph(`${c.pageId}/feed`,"POST",{message}));let permalink:string|null=null;try{const data=z.object({permalink_url:z.string().url().optional()}).parse(await graph(post.id,"GET",{fields:"permalink_url"}));permalink=data.permalink_url||null;}catch{}await repo.finalize(job,post.id,permalink);}return repo.get(id);
    }
    if(job.platform==="instagram"){
      if(job.status==="approved"&&await repo.claim(id,"approved","creating_container")){const data=idResponse.parse(await graph(`${c.instagramId}/media`,"POST",{media_type:"REELS",video_url:videoUrl,caption,share_to_feed:"true"}));await repo.update(id,{status:"container_created",external_container_id:data.id});}
      job=(await repo.get(id))!;
      if(["container_created","processing"].includes(job.status)&&job.external_container_id){const state=z.object({status_code:z.string()}).parse(await graph(job.external_container_id,"GET",{fields:"status_code"}));if(state.status_code==="ERROR"||state.status_code==="EXPIRED")await repo.update(id,{status:"failed",error_code:`IG_${state.status_code}`,error_message:"Instagram konnte den Mediencontainer nicht verarbeiten."});else if(state.status_code==="FINISHED")await repo.update(id,{status:"ready"});else await repo.update(id,{status:"processing",provider_state:JSON.stringify({statusCode:state.status_code})});}
      job=(await repo.get(id))!;
      if(job.status==="ready"&&job.external_container_id&&await repo.claim(id,"ready","publishing")){const published=idResponse.parse(await graph(`${c.instagramId}/media_publish`,"POST",{creation_id:job.external_container_id}));let permalink:string|null=null;try{const media=z.object({permalink:z.string().url().optional()}).parse(await graph(published.id,"GET",{fields:"permalink"}));permalink=media.permalink||null;}catch{/* publication succeeded; permalink can be reconciled later */}await repo.finalize(job,published.id,permalink);}
    }else{
      if(job.status==="approved"&&await repo.claim(id,"approved","creating_container")){const start=z.object({video_id:z.string(),upload_url:z.string().url().optional()}).parse(await graph(`${c.pageId}/video_reels`,"POST",{upload_phase:"start"}));await repo.update(id,{status:"fb_initialized",external_container_id:start.video_id,provider_state:JSON.stringify({uploadUrl:start.upload_url||`https://rupload.facebook.com/video-upload/${c.version||"v25.0"}/${start.video_id}`})});}
      job=(await repo.get(id))!;
      if(job.status==="fb_initialized"&&job.external_container_id&&await repo.claim(id,"fb_initialized","fb_uploading")){const uploadUrl=String(job.provider_state?.uploadUrl||"");const response=await fetch(uploadUrl,{method:"POST",headers:{Authorization:`OAuth ${c.token}`,file_url:videoUrl},redirect:"error",signal:AbortSignal.timeout(30_000)});if(!response.ok)throw Object.assign(new Error("Facebook-Reel-Upload abgelehnt."),{status:response.status});await repo.update(id,{status:"fb_uploaded"});}
      job=(await repo.get(id))!;
      if(job.status==="fb_uploaded"&&job.external_container_id&&await repo.claim(id,"fb_uploaded","publishing")){await graph(`${c.pageId}/video_reels`,"POST",{upload_phase:"finish",video_id:job.external_container_id,video_state:"PUBLISHED",description:caption,title:String(content.title||content.product||"Affiliate Reel").slice(0,255)});let permalink:string|null=null;try{const video=z.object({permalink_url:z.string().url().optional()}).parse(await graph(job.external_container_id,"GET",{fields:"permalink_url"}));permalink=video.permalink_url||null;}catch{}await repo.finalize(job,job.external_container_id,permalink);}
    }
  }catch(error){const status=typeof error==="object"&&error&&"status" in error?Number(error.status):0;const current=await repo.get(id);if(current&&["creating_container","fb_uploading","publishing"].includes(current.status)&&(!status||status>=500))await repo.update(id,{status:"unknown",error_code:"META_RESPONSE_UNKNOWN",error_message:"Meta-Antwort unklar; kein automatischer Neuversuch, um Doppelveröffentlichung zu verhindern."});else await repo.update(id,{status:"failed",error_code:`META_${status||"ERROR"}`,error_message:error instanceof Error?error.message:"Meta Publishing fehlgeschlagen."});}
  return repo.get(id);
}

export async function publishApprovedContentVersion(contentVersionId:string){const db=getDatabase();const r=await db.query("SELECT platform FROM content_versions WHERE id=$1",[contentVersionId]);const platform=r.rows[0]?.platform;if(platform!=="instagram"&&platform!=="facebook")throw new Error("Keine eindeutige freigegebene Zielplattform gespeichert.");const id=await publishingRepository(db).create(contentVersionId,platform);return advancePublishing(id);}
