import { createHash } from "node:crypto";
import { getDatabase, type Database } from "../memory/db";
import type { HumanIntent } from "./intent";

export type ApprovalContext={conversation_id:string;approval_id:string;kind:"RENDER_COST"|"CONTENT_PUBLISH"|"CAPABILITY_PROPOSAL";production_request_id:string|null;content_version_id:string|null;capability_proposal_id:string|null;status:string};
export function whatsappRepository(db:Database=getDatabase()){
  return {
    async claimEvent(eventId:string,raw:string){const hash=createHash("sha256").update(raw).digest("hex");const r=await db.query("INSERT INTO webhook_events(provider,event_id,payload_hash,status) VALUES('whatsapp',$1,$2,'received') ON CONFLICT DO NOTHING RETURNING event_id",[eventId,hash]);return r.rows.length===1;},
    async eventStatus(eventId:string,status:"ignored"|"processed"|"failed"){await db.query("UPDATE webhook_events SET status=$2,processed_at=now() WHERE provider='whatsapp' AND event_id=$1",[eventId,status]);},
    async openContext(sender:string){const r=await db.query(`SELECT c.id AS conversation_id,a.id AS approval_id,a.kind,a.production_request_id,a.content_version_id,a.capability_proposal_id,a.status
      FROM conversation_contexts c JOIN approval_requests a ON a.id=c.approval_request_id WHERE c.sender_hash=$1 AND c.status='open' AND a.status='AWAITING_HUMAN_APPROVAL' ORDER BY c.created_at DESC LIMIT 1`,[sender]);return r.rows[0] as ApprovalContext|undefined;},
    async record(context:ApprovalContext,sender:string,intent:HumanIntent,raw:string){await db.query("INSERT INTO human_instructions(id,approval_request_id,sender_hash,intent,target,instruction,raw_text) VALUES($1,$2,$3,$4,$5,$6,$7)",[crypto.randomUUID(),context.approval_id,sender,intent.intent,intent.target,intent.instruction,raw.slice(0,4000)]);},
    async reject(context:ApprovalContext,text:string){return db.transaction(async sql=>{const now=new Date().toISOString();await sql.query("UPDATE approval_requests SET status='REJECTED',decision_text=$2,decided_at=$3 WHERE id=$1 AND status='AWAITING_HUMAN_APPROVAL'",[context.approval_id,text,now]);if(context.production_request_id)await sql.query("UPDATE production_requests SET status='rejected',updated_at=$2 WHERE id=$1",[context.production_request_id,now]);if(context.content_version_id)await sql.query("UPDATE content_versions SET status='rejected' WHERE id=$1",[context.content_version_id]);if(context.capability_proposal_id)await sql.query("UPDATE capability_proposals SET status='REJECTED',decided_at=$2 WHERE id=$1",[context.capability_proposal_id,now]);await sql.query("UPDATE conversation_contexts SET status='closed',updated_at=$2 WHERE id=$1",[context.conversation_id,now]);});},
    async revision(context:ApprovalContext,text:string){return db.transaction(async sql=>{const now=new Date().toISOString();await sql.query("UPDATE approval_requests SET status='REVISION_REQUESTED',decision_text=$2,decided_at=$3 WHERE id=$1 AND status='AWAITING_HUMAN_APPROVAL'",[context.approval_id,text,now]);if(context.production_request_id)await sql.query("UPDATE production_requests SET status='planned',updated_at=$2 WHERE id=$1",[context.production_request_id,now]);if(context.content_version_id)await sql.query("UPDATE content_versions SET status='revision_requested' WHERE id=$1",[context.content_version_id]);await sql.query("UPDATE conversation_contexts SET status='closed',updated_at=$2 WHERE id=$1",[context.conversation_id,now]);});},
    async approveNonRender(context:ApprovalContext,intent:HumanIntent){return db.transaction(async sql=>{const now=new Date().toISOString();await sql.query("UPDATE approval_requests SET status='APPROVED',decision_text=$2,approved_at=$3,decided_at=$3 WHERE id=$1 AND status='AWAITING_HUMAN_APPROVAL'",[context.approval_id,intent.instruction,now]);if(context.content_version_id)await sql.query("UPDATE content_versions SET status='approved',approved_at=$2 WHERE id=$1",[context.content_version_id,now]);if(context.capability_proposal_id)await sql.query("UPDATE capability_proposals SET status=$2,decided_at=$3 WHERE id=$1",[context.capability_proposal_id,intent.intent==="APPROVE_PERMANENTLY"?"APPROVED_PERMANENTLY":"APPROVED_ONCE",now]);await sql.query("UPDATE conversation_contexts SET status='closed',updated_at=$2 WHERE id=$1",[context.conversation_id,now]);});},
  };
}
